# ðŸ”¹UFC ETL

## 1. Import Libraries and Setup Environment

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Visualization Config
sns.set(style="whitegrid")

## 2. Load Data

In [10]:
project_root = '/home/mfourier/ufc-predictor'
file_path = f'{project_root}/data/raw/ufc_raw.csv'
df = pd.read_csv(file_path)
print(f"Data loaded: {df.shape[0]} rows and {df.shape[1]} columns.")

Data loaded: 6541 rows and 118 columns.

## 3. Preview

In [11]:
# Preview the first few records
display(df.head())

# General dataset information
df.info()

,RedFighter,BlueFighter,RedOdds,BlueOdds,RedExpectedValue,BlueExpectedValue,Date,Location,Country,Winner,...,FinishDetails,FinishRound,FinishRoundTime,TotalFightTimeSecs,RedDecOdds,BlueDecOdds,RSubOdds,BSubOdds,RKOOdds,BKOOdds
0,Colby Covington,Joaquin Buckley,205.0,-250.0,205.0000,40.0000,2024-12-14,"Tampa, Florida, USA",USA,Blue,...,NaN,3.0,4:42,882.0,300.0,175.0,1800.0,2000.0,1100.0,150.0
1,Cub Swanson,Billy Quarantillo,124.0,-148.0,124.0000,67.5676,2024-12-14,"Tampa, Florida, USA",USA,Red,...,Punch,3.0,1:36,696.0,250.0,NaN,1800.0,NaN,450.0,NaN
2,Manel Kape,Bruno Silva,-395.0,310.0,25.3165,310.0000,2024-12-14,"Tampa, Florida, USA",USA,Red,...,Punches,3.0,1:57,717.0,-105.0,550.0,900.0,1800.0,225.0,1100.0
3,Vitor Petrino,Dustin Jacoby,-340.0,270.0,29.4118,270.0000,2024-12-14,"Tampa, Florida, USA",USA,Blue,...,Punch,3.0,3:44,824.0,240.0,500.0,550.0,3000.0,110.0,800.0
4,Adrian Yanez,Daniel Marcos,185.0,-225.0,185.0000,44.4444,2024-12-14,"Tampa, Florida, USA",USA,Blue,...,NaN,3.0,5:00,900.0,450.0,150.0,2200.0,2200.0,450.0,200.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6541 entries, 0 to 6540
Columns: 118 entries, RedFighter to BKOOdds
dtypes: bool(1), float64(60), int64(43), object(14)
memory usage: 5.8+ MB

## 4. Check

In [12]:
# Null values check
nulls = df.isnull().sum()
print("\nNull values per column:\n", nulls[nulls > 0])

# Duplicate analysis
duplicates = df.duplicated().sum()
print(f"\nDuplicate rows: {duplicates}")

Null values per column:
 RedOdds                   227
BlueOdds                  226
RedExpectedValue          227
BlueExpectedValue         226
BlueAvgSigStrLanded       930
BlueAvgSigStrPct          765
BlueAvgSubAtt             832
BlueAvgTDLanded           833
BlueAvgTDPct              842
BlueStance                  3
RedAvgSigStrLanded        455
RedAvgSigStrPct           357
RedAvgSubAtt              357
RedAvgTDLanded            357
RedAvgTDPct               367
EmptyArena               1499
BMatchWCRank             5339
RMatchWCRank             4760
RWFlyweightRank          6445
RWFeatherweightRank      6532
RWStrawweightRank        6395
RWBantamweightRank       6387
RHeavyweightRank         6355
RLightHeavyweightRank    6357
RMiddleweightRank        6359
RWelterweightRank        6349
RLightweightRank         6357
RFeatherweightRank       6364
RBantamweightRank        6360
RFlyweightRank           6352
RPFPRank                 6288
BWFlyweightRank          6468
BWFeatherweightRank      6540
BWStrawweightRank        6441
BWBantamweightRank       6434
BHeavyweightRank         6393
BLightHeavyweightRank    6421
BMiddleweightRank        6404
BWelterweightRank        6421
BLightweightRank         6421
BFeatherweightRank       6417
BBantamweightRank        6422
BFlyweightRank           6410
BPFPRank                 6474
Finish                    238
FinishDetails            3643
FinishRound               622
FinishRoundTime           622
TotalFightTimeSecs        622
RedDecOdds               1087
BlueDecOdds              1117
RSubOdds                 1336
BSubOdds                 1360
RKOOdds                  1334
BKOOdds                  1361
dtype: int64

Duplicate rows: 0

## 5. Data Cleaning

In [13]:
# Drop irrelevant columns (e.g., IDs or redundant columns)
#irrelevant = ['fight_id', 'fighter_id', 'event_id']
#df.drop(columns=irrelevant, inplace=True, errors='ignore')

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Drop columns with too many null values (threshold: 30%)
threshold = 0.3 * len(df)
cols_to_drop = [col for col in df.columns if df[col].isnull().sum() > threshold]
df.drop(columns=cols_to_drop, inplace=True)

# Fill remaining null values with mean or mode, depending on the data type
for col in df.columns:
    if df[col].dtype == 'object':
        mode = df[col].mode()[0]
        df[col] = df[col].fillna(mode)
    else:
        mean = df[col].mean()
        df[col] = df[col].fillna(mean)

## 6. Preview Clean Data

In [14]:
# Preview the first few records
display(df.head())

# General dataset information
df.info()

,RedFighter,BlueFighter,RedOdds,BlueOdds,RedExpectedValue,BlueExpectedValue,Date,Location,Country,Winner,...,Finish,FinishRound,FinishRoundTime,TotalFightTimeSecs,RedDecOdds,BlueDecOdds,RSubOdds,BSubOdds,RKOOdds,BKOOdds
0,Colby Covington,Joaquin Buckley,205.0,-250.0,205.0000,40.0000,2024-12-14,"Tampa, Florida, USA",USA,Blue,...,KO/TKO,3.0,4:42,882.0,300.0,175.000000,1800.0,2000.000000,1100.0,150.000000
1,Cub Swanson,Billy Quarantillo,124.0,-148.0,124.0000,67.5676,2024-12-14,"Tampa, Florida, USA",USA,Red,...,KO/TKO,3.0,1:36,696.0,250.0,425.889565,1800.0,1102.388149,450.0,636.803475
2,Manel Kape,Bruno Silva,-395.0,310.0,25.3165,310.0000,2024-12-14,"Tampa, Florida, USA",USA,Red,...,KO/TKO,3.0,1:57,717.0,-105.0,550.000000,900.0,1800.000000,225.0,1100.000000
3,Vitor Petrino,Dustin Jacoby,-340.0,270.0,29.4118,270.0000,2024-12-14,"Tampa, Florida, USA",USA,Blue,...,KO/TKO,3.0,3:44,824.0,240.0,500.000000,550.0,3000.000000,110.0,800.000000
4,Adrian Yanez,Daniel Marcos,185.0,-225.0,185.0000,44.4444,2024-12-14,"Tampa, Florida, USA",USA,Blue,...,S-DEC,3.0,5:00,900.0,450.0,150.000000,2200.0,2200.000000,450.0,200.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6541 entries, 0 to 6540
Data columns (total 89 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   RedFighter                   6541 non-null   object
 1   BlueFighter                  6541 non-null   object
 2   RedOdds                      6541 non-null   float64
 3   BlueOdds                     6541 non-null   float64
 4   RedExpectedValue             6541 non-null   float64
 5   BlueExpectedValue            6541 non-null   float64
 6   Date                         6541 non-null   object
 7   Location                     6541 non-null   object
 8   Country                      6541 non-null   object
 9   Winner                       6541 non-null   object
 10  TitleBout                    6541 non-null   bool
 11  WeightClass                  6541 non-null   object
 12  Gender                       6541 non-null   object
 13  NumberOfRounds               6541 non-null   int64
 14  BlueCurrentLoseStreak        6541 non-null   int64
 15  BlueCurrentWinStreak         6541 non-null   int64
 16  BlueDraws                    6541 non-null   int64
 17  BlueAvgSigStrLanded          6541 non-null   float64
 18  BlueAvgSigStrPct             6541 non-null   float64
 19  BlueAvgSubAtt                6541 non-null   float64
 20  BlueAvgTDLanded              6541 non-null   float64
 21  BlueAvgTDPct                 6541 non-null   float64
 22  BlueLongestWinStreak         6541 non-null   int64
 23  BlueLosses                   6541 non-null   int64
 24  BlueTotalRoundsFought        6541 non-null   int64
 25  BlueTotalTitleBouts          6541 non-null   int64
 26  BlueWinsByDecisionMajority   6541 non-null   int64
 27  BlueWinsByDecisionSplit      6541 non-null   int64
 28  BlueWinsByDecisionUnanimous  6541 non-null   int64
 29  BlueWinsByKO                 6541 non-null   int64
 30  BlueWinsBySubmission         6541 non-null   int64
 31  BlueWinsByTKODoctorStoppage  6541 non-null   int64
 32  BlueWins                     6541 non-null   int64
 33  BlueStance                   6541 non-null   object
 34  BlueHeightCms                6541 non-null   float64
 35  BlueReachCms                 6541 non-null   float64
 36  BlueWeightLbs                6541 non-null   int64
 37  RedCurrentLoseStreak         6541 non-null   int64
 38  RedCurrentWinStreak          6541 non-null   int64
 39  RedDraws                     6541 non-null   int64
 40  RedAvgSigStrLanded           6541 non-null   float64
 41  RedAvgSigStrPct              6541 non-null   float64
 42  RedAvgSubAtt                 6541 non-null   float64
 43  RedAvgTDLanded               6541 non-null   float64
 44  RedAvgTDPct                  6541 non-null   float64
 45  RedLongestWinStreak          6541 non-null   int64
 46  RedLosses                    6541 non-null   int64
 47  RedTotalRoundsFought         6541 non-null   int64
 48  RedTotalTitleBouts           6541 non-null   int64
 49  RedWinsByDecisionMajority    6541 non-null   int64
 50  RedWinsByDecisionSplit       6541 non-null   int64
 51  RedWinsByDecisionUnanimous   6541 non-null   int64
 52  RedWinsByKO                  6541 non-null   int64
 53  RedWinsBySubmission          6541 non-null   int64
 54  RedWinsByTKODoctorStoppage   6541 non-null   int64
 55  RedWins                      6541 non-null   int64
 56  RedStance                    6541 non-null   object
 57  RedHeightCms                 6541 non-null   float64
 58  RedReachCms                  6541 non-null   float64
 59  RedWeightLbs                 6541 non-null   int64
 60  RedAge                       6541 non-null   int64
 61  BlueAge                      6541 non-null   int64
 62  LoseStreakDif                6541 non-null   int64
 63  WinStreakDif                 6541 non-null   int64
 64  LongestWinStreakDif          6541 non-null   int64
 65  WinDif                       6541 non-null   int64
 66  LossDif                      6541 non-null   int64
 67  TotalRoundDif                6541 non-null   int64
 68  TotalTitleBoutDif            6541 non-null   int64
 69  KODif                        6541 non-null   int64
 70  SubDif                       6541 non-null   int64
 71  HeightDif                    6541 non-null   float64
 72  ReachDif                     6541 non-null   float64
 73  AgeDif                       6541 non-null   int64
 74  SigStrDif                    6541 non-null   float64
 75  AvgSubAttDif                 6541 non-null   float64
 76  AvgTDDif                     6541 non-null   float64
 77  EmptyArena                   6541 non-null   float64
 78  BetterRank                   6541 non-null   object
 79  Finish                       6541 non-null   object
 80  FinishRound                  6541 non-null   float64
 81  FinishRoundTime              6541 non-null   object
 82  TotalFightTimeSecs           6541 non-null   float64
 83  RedDecOdds                   6541 non-null   float64
 84  BlueDecOdds                  6541 non-null   float64
 85  RSubOdds                     6541 non-null   float64
 86  BSubOdds                     6541 non-null   float64
 87  RKOOdds                      6541 non-null   float64
 88  BKOOdds                      6541 non-null   float64
dtypes: bool(1), float64(32), int64(43), object(13)
memory usage: 4.4+ MB

## 7. Check Clean Data

In [15]:
# Null values check
nulls = df.isnull().sum()
print("\nNull values per column:\n", nulls[nulls > 0])

# Duplicate analysis
duplicates = df.duplicated().sum()
print(f"\nDuplicate rows: {duplicates}")

Null values per column:
 Series([], dtype: int64)

Duplicate rows: 0

## 6. Save

In [16]:
# Save the cleaned file
df.to_csv(f'{project_root}/data/processed/ufc_etl.csv', index=False)
print("\nETL file saved as 'ufc_etl.csv'.")

ETL file saved as 'ufc_etl.csv'.